apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.accounts.views import SignUpView, CustomLoginView
# from apps.accounts.views import CustomLoginView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

apps/chats/urls.py
from django.urls import path

from apps.chats.views import ChatListTemplate, ChatTemplate

app_name = 'chats'

urlpatterns = [
    path('', ChatListTemplate.as_view(), name='chats_list'),
    path('<slug:slug>/', ChatTemplate.as_view(), name='chat'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.chats.urls', namespace='chats')),
    path('admin/', admin.site.urls),
]

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

from utilities.common_abstract_models import BaseAbstract


class User(AbstractUser, BaseAbstract):
    email = models.EmailField(unique=True)
    groups = models.ManyToManyField(
        Group,
        verbose_name="Groups",
        blank=True,
        related_name="custom_users",
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name="User Permissions",
        blank=True,
        related_name="custom_users",
    )

apps/chats/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

from utilities.common_abstract_models import BaseAbstract


class Chat(BaseAbstract):
    name = models.CharField(
        verbose_name="Name",
        max_length=255,
    )
    slug = AutoSlugField(
        verbose_name="Slug",
        populate_from='name',
        unique=True,
        blank=True,
    )

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        super(Chat, self).save(*args, **kwargs)

    class Meta:
        db_table = 'chat'
        ordering = ('-created_at',)

apps/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

apps/chats/forms.py
from django import forms

from apps.chats.models import Chat


class ChatCreateForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = (
            'name',
        )

apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.views.generic import FormView

from apps.accounts.forms import SignUpForm


class CustomLoginView(LoginView):
    template_name = 'login.html'

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return super(CustomLoginView, self).form_invalid(form)


class SignUpView(FormView):
    template_name = 'signup.html'
    form_class = SignUpForm
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super(SignUpView, self).form_valid(form)

apps/chats/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.views.generic import TemplateView, FormView

from apps.chats import services as chat_services
from apps.chats.forms import ChatCreateForm
from apps.chats.models import Chat
from services.redis import RedisService


class ChatListTemplate(LoginRequiredMixin, FormView):
    template_name = 'chats.html'
    form_class = ChatCreateForm
    extra_context = {'chats': chat_services.get_all_chats()}
    success_url = '/'

    def form_valid(self, form):
        instance: Chat = form.save()
        # redirect to new chat page
        self.success_url += instance.slug
        messages.success(self.request, 'Chat created')
        return super(ChatListTemplate, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Chat name already exists')
        return super(ChatListTemplate, self).form_invalid(form)


class ChatTemplate(LoginRequiredMixin, TemplateView):
    template_name = 'chat.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        context['chat'] = chat_services.get_chat_by_slug(slug=slug)

        # Retrieve chat messages from Redis
        chat_messages = RedisService().get_chat_messages(chat_slug=slug)
        context['chat_messages'] = chat_messages
        return context

apps/accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Log in | {% endblock %}

{% block content %}
  <div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Log in</h1>
  </div>

  <form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
      <label class="text-white">Username</label>
      <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>


    <div class="mb-5">
      <label class="text-white">Password</label>
      <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
            <p>{{ error|escape }}</p>
          </div>
        {% endfor %}
      {% endfor %}
    {% endif %}

    <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Log in</button>
  </form>
{% endblock %}

apps/accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Sign up</h1>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>

        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Email</label>

        <input type="email" name="email" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>

        <input type="password" name="password1" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Repeat password</label>

        <input type="password" name="password2" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %} 
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Submit</button>
</form>
{% endblock %}

apps/chats/templates/chat.html
{% extends 'base.html' %}

{% block title %}{{ chat.name }} | {% endblock %}

{% block content %}
  <div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">{{ chat.name }}</h1>
  </div>

  <div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">
      {% for message in chat_messages %}
        <b>{{ message.username }}</b>: {{ message.message }}<br>{% endfor %}
    </div>
  </div>

  <div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <form method="post" action="." class="flex">
      <input type="text" name="content" class="flex-1 mr-3" placeholder="Your message..." id="chat-message-input">

      <button
          class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700"
          id="chat-message-submit"
      >Submit
      </button>
    </form>
    <div id="error-message" class="mt-3 mb-5 p-4 rounded-xl bg-red-300 text-white"></div>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    // Get the chat slug and username from your Django template
    const chatName = '{{ chat.slug }}';
    const username = '{{ request.user.username }}';
    const errorMessage = document.getElementById('error-message');
    errorMessage.hidden = true;

    // Create the WebSocket URL based on the current host and chatName
    const chatSocketURL = `ws://${window.location.host}/ws/${chatName}/`;
    const chatSocket = new WebSocket(chatSocketURL);

    // Log the WebSocket URL for debugging
    console.log('WebSocket URL:', chatSocket.url);

    // Handle WebSocket events
    chatSocket.onclose = (event) => {
      console.log('WebSocket connection closed:', event);
    };

    chatSocket.onmessage = (event) => {
      const data = JSON.parse(event.data);
      console.log('received:', data);

      if (data.message) {
        // Display the received message in the chat box
        const chatMessages = document.querySelector('#chat-messages');
        chatMessages.innerHTML += `<b>${data.username}</b>: ${data.message}<br>`;

      } else if (data.error) {
        // Display the error message
        errorMessage.hidden = false;
        errorMessage.innerHTML = `<p>${data.error}</p>`;
        setTimeout(() => {
          errorMessage.hidden = true
        }, 3000);
      }

      // Scroll to the bottom of the chat box
      scrollToBottom();
    };

    chatSocket.onerror = (event) => {
      console.error('WebSocket error:', event);
    };

    // Set up event listeners for chat input
    const messageInput = document.querySelector('#chat-message-input');
    const messageSubmitButton = document.querySelector('#chat-message-submit');

    messageInput.focus();

    messageInput.addEventListener('keyup', (e) => {
      if (e.key === 'Enter') {
        messageSubmitButton.click();
      }
    });

    messageSubmitButton.addEventListener('click', (e) => {
      e.preventDefault();

      // Get the message from the input field
      const message = messageInput.value;

      // Send the message to the server via WebSocket
      chatSocket.send(JSON.stringify({
        message,
        username,
        chat: chatName,
      }));

      // Clear the input field
      messageInput.value = '';
    });

    // Function to scroll to the bottom of the chat box
    const scrollToBottom = () => {
      const chatMessages = document.getElementById('chat-messages');
      chatMessages.scrollTop = chatMessages.scrollHeight;
    };

    // Scroll to the bottom on page load
    window.addEventListener('load', scrollToBottom);

  </script>
{% endblock %}

apps/chats/templates/chats.html
{% extends 'base.html' %}

{% block title %}Chats | {% endblock %}

{% block content %}
  <div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Chats</h1>
  </div>

  <div class="w-full flex flex-wrap items-center">
    {% for chat in chats %}
      <div class="w-full lg:w-1/4 px-3 py-3">
        <div class="p-4 bg-white shadow rounded-xl text-center">
          <h2 class="mb-5 text-2xl font-semibold">{{ chat.name }}</h2>

          <a href="{% url 'chats:chat' chat.slug %}"
             class="px-5 py-3 block rounded-xl text-white bg-teal-600 hover:bg-teal-700">Join</a>
        </div>
      </div>
    {% endfor %}

    <div class="w-full lg:w-1/4 px-3 py-3">
      <div class="p-4 bg-white shadow rounded-xl text-center">
        <h2 class="mb-5 text-2xl font-semibold">New Chat</h2>
        <form  method="post">
          {% csrf_token %}
          <div class="mb-4">
            <input type="text" name="name" id="chat_name" placeholder="Chat Name"
                   class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:border-teal-500">
          </div>
          <button type="submit" class="px-5 py-3 block rounded-xl text-white bg-teal-600 hover:bg-teal-700">Create
          </button>
        </form>
      </div>
    </div>

  </div>
{% endblock %}

site_content/templates/base.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock %}Realtime Chats Django</title>

  <script src="https://cdn.tailwindcss.com"></script>

  <style>
      .messages {
          height: 400px;
          overflow-y: auto;
      }
  </style>
</head>

<body class="bg-teal-600">
<nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
  <div>
    <a href="#" class="text-xl text-white">Realtime Chats Django</a>
  </div>

  <div class="flex items-center space-x-4">
    {% if request.user.is_authenticated %}
      <a href="{% url 'chats:chats_list' %}" class="text-white hover:text-gray-200">Chats</a>

      <a href="{% url 'accounts:logout' %}" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Log
        out</a>
    {% else %}
      <a href="{% url 'accounts:login' %}" class="text-white hover:text-gray-200">Log in</a>

      <a href="{% url 'accounts:signup' %}" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Sign
        up</a>
    {% endif %}
  </div>
</nav>

<div>
  {% include 'common/alert.html' %}
</div>

{% block content %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

site_content/templates/common/alert.html
{% for message in messages %}
  <div id="base_alerts" class="{{ message.tags }} alert-dismissible p-4 rounded-md border">
    <button type="button" class="close text-gray-600 hover:text-black" data-dismiss="alert">
      &times;
    </button>
    {{ message }}
  </div>
{% endfor %}

{% block scripts %}
  <script>
    setTimeout(() => {
      const baseAlerts = document.getElementById("base_alerts");
      if (baseAlerts) {
        baseAlerts.style.transition = "height 0.5s ease";
        baseAlerts.style.height = "0px";
        setTimeout(() => {
          baseAlerts.style.display = "none";
        }, 500);
      }
    }, 7000);
  </script>
{% endblock scripts %}